{{- if .Values.observability.serviceMonitor.enabled }}
{{- range $name, $svc := .Values.services }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "oms-services.fullname" $ }}-{{ $name }}
  labels:
    app.kubernetes.io/name: {{ $name }}
    app.kubernetes.io/part-of: oms
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - {{ $.Release.Namespace }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $name }}
      app.kubernetes.io/part-of: oms
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 30s
      scrapeTimeout: 10s
---
{{- end }}
{{- end }}
